### ISSUE TITLE
Screen Size

### ISSUE THREAD

**Issue by ZeFish** [gkoh/furble#120]
I'll be honnest, I didn't take the time to look at the code, but here's my display. Evertything else works except the screen that seems on the smaller size.
![IMG_8487_2048x1536_U_100_G10_Flickr  500px](https://github.com/user-attachments/assets/a1b7c9cb-17e4-4432-8ac4-a05f64a81ded)

**Comment by gkoh** [comment]
@ZeFish That looks like a M5StickC Plus2 (based on the case colour).
I'm testing with `v2.1.0+1`.

If I flash the M5StickC firmware, I get exactly what you see.
If I flash the M5StickC Plus firmware (2nd option in the web installer), I get the right screen resolution.

Can you confirm you are using the correct firmware?

**Comment by gkoh** [comment]
Assuming incorrect firmware, this should be prevented in future with #123.

**Comment by ZeFish** [comment]
You are right, I originally install the firmware from the github source code, didn't think much of it. Now from the web installer it works. Thanks for taking the time!

**Comment by gkoh** [comment]
> You are right, I originally install the firmware from the github source code, didn't think much of it. Now from the web installer it works. Thanks for taking the time!

No problem, glad you worked it out (and it's all working for you).
