### ISSUE TITLE
Add simultaneous multiple camera connection

### ISSUE THREAD

**Issue by gkoh** [gkoh/furble#128]
With the shift to expose the EPS32's underlying FreeRTOS, we can further abstract `furble`'s components in meaningful ways.
By adding per-camera tasks and funnelling UI inputs through a command queue, it will be possible to connect to and control multiple cameras at the same time.

To preserve the current 'easy' 'click-click-click' experience, hide the feature behind a setting and default to false.

**Comment by matthudsonau** [comment]
Had someone ask about doing this last month. Good timing

**Comment by gkoh** [comment]
> Had someone ask about doing this last month. Good timing

Ha!
All the refactoring over the past few months has been aimed at implementing this :slightly_smiling_face: 

Will be great to get real-world feedback on it when it's done.

**Comment by matthudsonau** [comment]
Well, once work gets done with firing us (long story) I'll hopefully have a bit of time to test things

**Comment by gkoh** [comment]
> Well, once work gets done with firing us (long story) I'll hopefully have a bit of time to test things

:open_mouth:

**Comment by gkoh** [comment]
A pre-release with this feature is in [2.2.0-rc2](https://github.com/gkoh/furble/releases/tag/v2.2.0-rc2)
