### ISSUE TITLE
Installation Info

### ISSUE THREAD

**Issue by dimitrij2k** [gkoh/furble#34]
Hey, Congratulation for a very nice 1.0 Version and a bin. I flashed the bin file with ESPHome Alllication and it works perfect. I tried every Theme/Settigs and im really happy. Especially the „focus only“ - i love it - THX! Donation coild be also add to the main page ☺️

Now to the suggestion: maybe you could edit, that the installation is easy with ESPHome and link to the App 😉

**Comment by gkoh** [comment]
Thanks for the feedback @dimitrij2k I've been experimenting with M5Stack's own app, it might get even easier for Windows users.
