### ISSUE TITLE
Support for M5StickC PLUS2 

### ISSUE THREAD

**Issue by ress122** [gkoh/furble#59]
Will there be a support release for M5StickC PLUS2?
Thanks

**Comment by gkoh** [comment]
> Will there be a support release for M5StickC PLUS2? Thanks

That's an extremely well timed question!
I was just looking into getting myself an M5StickC Plus2.

The answer is yes, but it will take several (or more) weeks.

**Comment by gkoh** [comment]
@ress122 Do you have an M5StickC Plus2 to test?

**Comment by ress122** [comment]
No I don't have one yet. Was looking into it.

**Comment by matthudsonau** [comment]
I've ordered a M5StickC Plus2. Happy to test when it arrives

**Comment by gkoh** [comment]
Just ordered a M5StickC Plus2 as well, the almost 2x battery life will make it _much_ more usable.

**Comment by matthudsonau** [comment]
Compiled with m5stick-c-plus build flag, appears functional

**Comment by gkoh** [comment]
> Compiled with m5stick-c-plus build flag, appears functional. Tested on a X-H2S (the 100ii is in for a service)

Excellent, the primary concern was the display (apparently pinout was modified).
However, if it ' just works', then we may be able to use just the single firmware image for both Plus and Plus2.

Mine is still in transit.

**Comment by matthudsonau** [comment]
> Excellent, the primary concern was the display (apparently pinout was modified). However, if it ' just works', then we may be able to use just the single firmware image for both Plus and Plus2.

Definitely didn't see any display issues. If that's the only real change then it's probably all good
