### ISSUE TITLE
Add per-remote identifier support

### ISSUE THREAD

**Issue by gkoh** [gkoh/furble#83]
If you have more than one remote they're all called `furble`.
This makes it difficult/messy if you're developing/testing or doing interesting things with multiple cameras and multiple remotes.

Add a way to identify the remote via name. Perhaps using some fragment of the ESP32 ChipID?

**Comment by matthudsonau** [comment]
I think defaulting to something unique is a great idea. Would be nice if it could be changed as well, but something tells me that that's a UI nightmare to do

**Comment by gkoh** [comment]
> I think defaulting to something unique is a great idea. Would be nice if it could be changed as well, but something tells me that that's a UI nightmare to do

Agreed, I'm also moving this to 2.0 because it's getting a bit challenging juggling remotes.
